/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicFloodSplatRouteImport } from './routes/api/public/flood/$'
import { Route as ApiPublicFloodSensor_dataRouteImport } from './routes/api/public/flood/sensor_data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFloodSplatRoute = ApiPublicFloodSplatRouteImport.update({
  id: '/api/public/flood/$',
  path: '/api/public/flood/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFloodSensor_dataRoute =
  ApiPublicFloodSensor_dataRouteImport.update({
    id: '/api/public/flood/sensor_data',
    path: '/api/public/flood/sensor_data',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/flood/$': typeof ApiPublicFloodSplatRoute
  '/api/public/flood/sensor_data': typeof ApiPublicFloodSensor_dataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/flood/$': typeof ApiPublicFloodSplatRoute
  '/api/public/flood/sensor_data': typeof ApiPublicFloodSensor_dataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/flood/$': typeof ApiPublicFloodSplatRoute
  '/api/public/flood/sensor_data': typeof ApiPublicFloodSensor_dataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/flood/$' | '/api/public/flood/sensor_data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/flood/$' | '/api/public/flood/sensor_data'
  id: '__root__' | '/' | '/api/public/flood/$' | '/api/public/flood/sensor_data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicFloodSplatRoute: typeof ApiPublicFloodSplatRoute
  ApiPublicFloodSensor_dataRoute: typeof ApiPublicFloodSensor_dataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flood/$': {
      id: '/api/public/flood/$'
      path: '/api/public/flood/$'
      fullPath: '/api/public/flood/$'
      preLoaderRoute: typeof ApiPublicFloodSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flood/sensor_data': {
      id: '/api/public/flood/sensor_data'
      path: '/api/public/flood/sensor_data'
      fullPath: '/api/public/flood/sensor_data'
      preLoaderRoute: typeof ApiPublicFloodSensor_dataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicFloodSplatRoute: ApiPublicFloodSplatRoute,
  ApiPublicFloodSensor_dataRoute: ApiPublicFloodSensor_dataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
